DROP TABLE IF EXISTS FLIGHT;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USER_X_ROLE;

DROP SEQUENCE IF EXISTS FLIGHT_SEQ;

CREATE SEQUENCE FLIGHT_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1;

CREATE TABLE FLIGHT(
	FLIGHT_NO VARCHAR(255) NOT NULL,
	DEPARTURE_PORT VARCHAR(10) NOT NULL,
	ARRIVAL_PORT VARCHAR(10) NOT NULL,
	DEPARTURE_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
	ARRIVAL_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
	AIRLINE VARCHAR(10) NOT NULL,
	PRIMARY KEY ( FLIGHT_NO )
);

CREATE TABLE USER(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL UNIQUE,
	PASSWORD VARCHAR(255) NOT NULL,
	PRIMARY KEY ( ID )
);

CREATE TABLE ROLE(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY ( ID )
);

CREATE TABLE USER_X_ROLE(
	USER_ID BIGINT NOT NULL,
	ROLE_ID INT NOT NULL,
	PRIMARY KEY ( USER_ID, ROLE_ID)
);