DROP TABLE IF EXISTS FLIGHT;
DROP SEQUENCE IF EXISTS FLIGHT_SEQ;

CREATE SEQUENCE FLIGHT_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1;

CREATE TABLE FLIGHT(
	FLIGHT_NO VARCHAR(255) NOT NULL,
	DEPARTURE_PORT VARCHAR(10) NOT NULL,
	ARRIVAL_PORT VARCHAR(10) NOT NULL,
	DEPARTURE_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
	ARRIVAL_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
	AIRLINE VARCHAR(10) NOT NULL,
	PRIMARY KEY ( FLIGHT_NO )
);