package com.fake.flightscheduler.repo;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

import org.assertj.core.util.Arrays;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import com.fake.flightscheduler.entity.Flight;

@SpringBootTest
public class FlightRepositoryTest {

	@Autowired
	private FlightRepository flightRepository;

	@Test
	public void testAutoGeneratedFlightNumber() {
		Flight flight = new Flight();
		flight.setAirline("PAL");
		flight.setArrivalPort("MEL");
		flight.setDeparturePort("SYD");
		flight.setArrivalTime(OffsetDateTime.parse("2020-06-11T18:25:23Z"));
		flight.setDepartureTime(OffsetDateTime.parse("2020-06-11T19:25:23Z"));
		Flight savedFlight = flightRepository.save(flight);
		assertEquals(flight.getAirline()+"1", savedFlight.getFlightNumber());
	}

	@Test
	public void testFindByAirlineIn() {
		Flight flight1 = new Flight();
		flight1.setAirline("QF");
		flight1.setArrivalPort("MEL");
		flight1.setDeparturePort("SYD");
		flight1.setArrivalTime(OffsetDateTime.parse("2020-06-11T18:25:23Z"));
		flight1.setDepartureTime(OffsetDateTime.parse("2020-06-11T19:25:23Z"));
		Flight flight2 = new Flight();
		flight2.setAirline("KY");
		flight2.setArrivalPort("SYD");
		flight2.setDeparturePort("MED");
		flight2.setArrivalTime(OffsetDateTime.parse("2020-06-11T18:25:23Z"));
		flight2.setDepartureTime(OffsetDateTime.parse("2020-06-11T19:25:23Z"));

		flightRepository.save(flight1);
		flightRepository.save(flight2);

		List<String> airlines = new ArrayList<String>();
		airlines.add("QF");
		List<Flight> flights = flightRepository.findByAirlineIn(airlines);
		assertEquals(1, flights.size());
	}

}